#!/bin/bash
# Compile Hermes proto files to Python

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
PROTO_DIR="$PROJECT_ROOT/protos"
OUTPUT_DIR="$PROJECT_ROOT/hermes/grpc/generated"

echo "Compiling Hermes proto files..."

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Compile proto files
python3 -m grpc_tools.protoc \
    -I"$PROTO_DIR" \
    --python_out="$OUTPUT_DIR" \
    --grpc_python_out="$OUTPUT_DIR" \
    --pyi_out="$OUTPUT_DIR" \
    "$PROTO_DIR/hermes.proto"

# Create __init__.py
cat > "$OUTPUT_DIR/__init__.py" << 'EOF'
"""
Generated gRPC code for Hermes API.

Auto-generated by compile_protos.sh - do not edit manually.
"""

from hermes.grpc.generated.hermes_pb2 import *
from hermes.grpc.generated.hermes_pb2_grpc import *
EOF

# Fix imports in generated files (grpc_tools generates relative imports incorrectly)
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    sed -i '' 's/import hermes_pb2/from hermes.grpc.generated import hermes_pb2/g' "$OUTPUT_DIR/hermes_pb2_grpc.py"
else
    # Linux
    sed -i 's/import hermes_pb2/from hermes.grpc.generated import hermes_pb2/g' "$OUTPUT_DIR/hermes_pb2_grpc.py"
fi

echo "Proto compilation complete. Output: $OUTPUT_DIR"
